### ISSUE TITLE
Google Tasks integration

### ISSUE THREAD

**Issue by xbili** [CS2103JAN2017-W15-B3/main#138]

**Comment by xbili** [comment]
Delete tasks that were added with a start time in Google tasks.

**Comment by mynameisyz** [comment]
Objectives
- [x] Push to GTask
- [ ] Pull (sync) from GTask

Sequence
- [ ] Add UUIDs to tasks
- [x] Build sync interface and syncManager class
- [x] Build syncClient interface and GtaskClient class
- [x] Integrate with ModelManager
- [ ] Multi-thread sync
- [x] Build commands to enable/disable sync
- [ ] Test cases

**Comment by mynameisyz** [comment]
Problems:
- Unlike Google Calendar, Google Task rejects task with user-defined ids. 
- ModelManager does not have any running loop. Syncing model and Gtask will require building another thread in model and use mutex to manage taskManager. Another way is to call model from sync and introduce a lot of coupling.
- Does not work with undo/redo.
