### ISSUE TITLE
UI revamp

### ISSUE THREAD

**Issue by xbili** [CS2103JAN2017-W15-B3/main#76]
The current user interface still reeks of the old design.

To be implemented incrementally in the following order:

- [ ] ~~Digital clock display~~
- [ ] Task cards
    - [x] Deadline colors
    ~~- [ ] Priority logos~~
- [x] Split pane into three separate panes, with all tasks residing in one pane (for now)
- [x] Command line input
- [x] Feedback/welcome message area
- [x] Change colors to fit color scheme
